name: Exercise 7

on:
 push:
   branches: [ "master" ]
 pull_request:
   branches: [ "master" ]

 workflow_dispatch:
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Ex_5 - Init
       run: g++ rect.cpp -o rect
       	    g++ sample.cpp -o sample
	    g++ struct.cpp -o struct
	    
     - name: Run exe_Files
       run: ./rect
            ./sample
	    ./struct